global using System.Reactive.Linq;
global using System.Runtime.CompilerServices;
global using System.Text.Json.Serialization;
global using Avalonia.Media;
global using DesktopApp.Common;
global using DesktopApp.Utilities;
global using DesktopApp.Utilities.Attributes;
global using DesktopApp.Utilities.Helpers;
global using JetBrains.Annotations;
global using ReactiveUI;
global using ReactiveUI.Fody.Helpers;
global using Splat;
global using static DesktopApp.Common.SplatHelpers;
global using DayOfWeek = DesktopApp.Common.DayOfWeek;
global using SeriLogLevel = Serilog.Events.LogEventLevel;
global using AvaLogLevel = Avalonia.Logging.LogEventLevel;
global using DisplayNameAttribute = DesktopApp.Utilities.Attributes.DisplayNameAttribute;
